import { amex, discover, mastercard, visa } from '../assets/icons';
import {
  carImage,
  carView2,
  carView3,
  blueRectangle1,
  blueRectangle2,
} from '../assets/images/index';

export const icons = [
  {
    label: 'visa icon',
    icon: visa,
  },
  {
    label: 'mastercard icon',
    icon: mastercard,
  },
  {
    label: 'american express icon',
    icon: amex,
  },
  {
    label: 'discover icon',
    icon: discover,
  },
];

export const headerText = [
  {
    title1: `The Best Platform`,
    title2: `for Car Rental`,
    subtitle1: `Ease of doing car rental safely and`,
    subtitle2: `reliably, and at a low price.`,
    background: blueRectangle1,
  },
  {
    title1: `Easy way to rent a`,
    title2: `car at a low price`,
    subtitle1: `Providing cheap car rental services`,
    subtitle2: `and safe and comfortable facilities.`,
    background: blueRectangle2,
  },
];

export const cars = [
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 3000,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'This is a test',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 70,
    transmissionType: 'manual',
    capacity: 1,
    price: 100,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Another test',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 70,
    transmissionType: 'manual',
    capacity: 5,
    price: 100,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 2,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 70,
    transmissionType: 'manual',
    capacity: 5,
    price: 100,
    discountPrice: 0,
    buttonText: 'More Info',
    reviews: 440,
    rating: 1,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 70,
    transmissionType: 'manual',
    capacity: 5,
    price: 100,
    discountPrice: 0,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 70,
    transmissionType: 'manual',
    capacity: 5,
    price: 100,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 70,
    transmissionType: 'manual',
    capacity: 5,
    price: 100,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 70,
    transmissionType: 'manual',
    capacity: 5,
    price: 100,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 70,
    transmissionType: 'manual',
    capacity: 5,
    price: 100,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 70,
    transmissionType: 'manual',
    capacity: 5,
    price: 100,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 70,
    transmissionType: 'manual',
    capacity: 5,
    price: 100,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 70,
    transmissionType: 'manual',
    capacity: 5,
    price: 100,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 70,
    transmissionType: 'manual',
    capacity: 5,
    price: 100,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 70,
    transmissionType: 'manual',
    capacity: 5,
    price: 100,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 70,
    transmissionType: 'manual',
    capacity: 5,
    price: 100,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 70,
    transmissionType: 'manual',
    capacity: 5,
    price: 100,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carView1: carImage,
    carView2: carView2,
    carView3: carView3,
    fuelTankSize: 70,
    transmissionType: 'manual',
    capacity: 5,
    price: 100,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
];

export const footerLinks = [
  {
    title: 'About',
    links: [
      { linkTitle: 'How it works', linkTo: '' },
      { linkTitle: 'Featured', linkTo: '' },
      { linkTitle: 'Partnership', linkTo: '' },
      { linkTitle: 'Bussiness Relation', linkTo: '' },
    ],
  },
  {
    title: 'Community',
    links: [
      { linkTitle: 'Events', linkTo: '' },
      { linkTitle: 'Blog', linkTo: '' },
      { linkTitle: 'Podcast', linkTo: '' },
      { linkTitle: 'Invite a friend', linkTo: '' },
    ],
  },
  {
    title: 'Socials',
    links: [
      { linkTitle: 'Discord', linkTo: '' },
      { linkTitle: 'Instagram', linkTo: '' },
      { linkTitle: 'Twitter', linkTo: '' },
      { linkTitle: 'Facebook', linkTo: '' },
    ],
  },
];
