import { amex, discover, mastercard, visa } from '../assets/icons';
import carImage from '../assets/images/carImage.png';

export const icons = [
  {
    label: 'visa icon',
    icon: visa,
  },
  {
    label: 'mastercard icon',
    icon: mastercard,
  },
  {
    label: 'american express icon',
    icon: amex,
  },
  {
    label: 'discover icon',
    icon: discover,
  },
];

export const cars = [
  {
    title: 'Koenigsegg',
    carType: 'Sport',
    carImage: carImage,
    fuelTankSize: 70,
    transmissionType: 'manual',
    numberOfPeople: 5,
    price: 100,
    discountPrice: 80,
    buttonText: 'More Info',
  },
  {
    title: 'Koenigsegg',
    carType: 'Sport',
    carImage: carImage,
    fuelTankSize: 70,
    transmissionType: 'Manual',
    numberOfPeople: 5,
    price: 100.0,
    discountPrice: 80.0,
    buttonText: 'More Info',
  },
  {
    title: 'Koenigsegg',
    carType: 'Sport',
    carImage: carImage,
    fuelTankSize: 70,
    transmissionType: 'Manual',
    numberOfPeople: 5,
    price: 100.0,
    discountPrice: 80.0,
    buttonText: 'More Info',
  },
  {
    title: 'Koenigsegg',
    carType: 'Sport',
    carImage: carImage,
    fuelTankSize: 70,
    transmissionType: 'Manual',
    numberOfPeople: 5,
    price: 100.0,
    discountPrice: 80.0,
    buttonText: 'More Info',
  },
  {
    title: 'Koenigsegg',
    carType: 'Sport',
    carImage: carImage,
    fuelTankSize: 70,
    transmissionType: 'Manual',
    numberOfPeople: 5,
    price: 100.0,
    discountPrice: 0,
    buttonText: 'More Info',
  },
  {
    title: 'Koenigsegg',
    carType: 'Sport',
    carImage: carImage,
    fuelTankSize: 70,
    transmissionType: 'Manual',
    numberOfPeople: 5,
    price: 100.0,
    discountPrice: 80.0,
    buttonText: 'More Info',
  },
  {
    title: 'Koenigsegg',
    carType: 'Sport',
    carImage: carImage,
    fuelTankSize: 70,
    transmissionType: 'Manual',
    numberOfPeople: 5,
    price: 100.0,
    discountPrice: 80.0,
    buttonText: 'More Info',
  },
  {
    title: 'Koenigsegg',
    carType: 'Sport',
    carImage: carImage,
    fuelTankSize: 70,
    transmissionType: 'Manual',
    numberOfPeople: 5,
    price: 100.0,
    discountPrice: 80.0,
    buttonText: 'More Info',
  },
  {
    title: 'Koenigsegg',
    carType: 'Sport',
    carImage: carImage,
    fuelTankSize: 70,
    transmissionType: 'Manual',
    numberOfPeople: 5,
    price: 100.0,
    discountPrice: 80.0,
    buttonText: 'More Info',
  },
  {
    title: 'Koenigsegg',
    carType: 'Sport',
    carImage: carImage,
    fuelTankSize: 70,
    transmissionType: 'Manual',
    numberOfPeople: 5,
    price: 100.0,
    discountPrice: 80.0,
    buttonText: 'More Info',
  },
  {
    title: 'Koenigsegg',
    carType: 'Sport',
    carImage: carImage,
    fuelTankSize: 70,
    transmissionType: 'Manual',
    numberOfPeople: 5,
    price: 100.0,
    discountPrice: 80.0,
    buttonText: 'More Info',
  },
];

export const footerLinks = [
  {
    title: 'About',
    links: [
      { linkTitle: 'How it works', linkTo: '' },
      { linkTitle: 'Featured', linkTo: '' },
      { linkTitle: 'Partnership', linkTo: '' },
      { linkTitle: 'Bussiness Relation', linkTo: '' },
    ],
  },
  {
    title: 'Community',
    links: [
      { linkTitle: 'Events', linkTo: '' },
      { linkTitle: 'Blog', linkTo: '' },
      { linkTitle: 'Podcast', linkTo: '' },
      { linkTitle: 'Invite a friend', linkTo: '' },
    ],
  },
  {
    title: 'Socials',
    links: [
      { linkTitle: 'Discord', linkTo: '' },
      { linkTitle: 'Instagram', linkTo: '' },
      { linkTitle: 'Twitter', linkTo: '' },
      { linkTitle: 'Facebook', linkTo: '' },
    ],
  },
];

export const pickupLocation = [
  'london',
  'bristol',
  'york',
  'birminham',
  'bath',
];
