import {
  amex,
  discover,
  mastercard,
  visa,
  dots,
  clock,
  calendar,
  navSearch,
  plus,
  home,
} from '../assets/icons';

import {
  carImage,
  carView2,
  carView3,
  blueRectangle1,
  blueRectangle2,
} from '../assets/images/index';

export const icons = [
  {
    label: 'visa icon',
    icon: visa,
  },
  {
    label: 'mastercard icon',
    icon: mastercard,
  },
  {
    label: 'american express icon',
    icon: amex,
  },
  {
    label: 'discover icon',
    icon: discover,
  },
];

export const headerText = [
  {
    title1: `The Best Platform`,
    title2: `for Car Rental`,
    subtitle1: `Ease of doing car rental safely and`,
    subtitle2: `reliably, and at a low price.`,
    background: blueRectangle1,
  },
  {
    title1: `Easy way to rent a`,
    title2: `car at a low price`,
    subtitle1: `Providing cheap car rental services`,
    subtitle2: `and safe and comfortable facilities.`,
    background: blueRectangle2,
  },
];

export const cars = [
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 15,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
  {
    title: 'Koenigsegg',
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    carType: 'Sport',
    carImages: [carImage, carView2, carView3],
    fuelTankSize: 20,
    transmissionType: 'manual',
    capacity: 5,
    price: 300,
    discountPrice: 80,
    buttonText: 'More Info',
    reviews: 440,
    rating: 4,
  },
];

export const footerLinks = [
  {
    title: 'About',
    links: [
      { linkTitle: 'How it works', linkTo: '' },
      { linkTitle: 'Featured', linkTo: '' },
      { linkTitle: 'Partnership', linkTo: '' },
      { linkTitle: 'Bussiness Relation', linkTo: '' },
    ],
  },
  {
    title: 'Community',
    links: [
      { linkTitle: 'Events', linkTo: '' },
      { linkTitle: 'Blog', linkTo: '' },
      { linkTitle: 'Podcast', linkTo: '' },
      { linkTitle: 'Invite a friend', linkTo: '' },
    ],
  },
  {
    title: 'Socials',
    links: [
      { linkTitle: 'Discord', linkTo: '' },
      { linkTitle: 'Instagram', linkTo: '' },
      { linkTitle: 'Twitter', linkTo: '' },
      { linkTitle: 'Facebook', linkTo: '' },
    ],
  },
];

export const formData = [
  {
    icon: dots,
    label: 'Location',
    dataSelects: ['Gianyar', 'Ubud', 'Badung', 'Singaraja'],
    key: 'location',
    placeholder: 'Select your city',
    errorMessage: 'Please select a city',
  },
  {
    icon: calendar,
    label: 'Pick-Up Date',
    key: 'dropOffDate',
    placeholder: 'Select your date',
    errorMessage: 'Please select a pick-up date',
  },
  {
    icon: clock,
    label: 'Pick-Up Time',
    key: 'dropOffTime',
    placeholder: 'Select your time',
    errorMessage: 'Please select a pick-up time',
  },
  {
    icon: calendar,
    label: 'Drop-Off Date',
    key: 'pickUpDate',
    placeholder: 'Select your date',
    errorMessage: 'Please select drop-off date',
  },
  {
    icon: clock,
    label: 'Drop-Off Time',
    key: 'pickUpTime',
    placeholder: 'Select your time',
    errorMessage: 'Please select drop-off time',
  },
];

export const CarCapacityLists = [
  {
    label: '2 Person',
    key: '2',
  },
  {
    label: '4 Person',
    key: '4',
  },
  {
    label: '6 person',
    key: '6',
  },
  {
    label: '8 Person',
    key: '8',
  },
];

export const carTypes = [
  {
    label: 'Sport',
    key: 'sport',
  },
  {
    label: 'MPV',
    key: 'mpv',
  },
  {
    label: 'Sedan',
    key: 'sedan',
  },
  {
    label: 'Coupe',
    key: 'coupe',
  },
  {
    label: 'Hatchback',
    key: 'hatchback',
  },
];

export const pickupLocation = [
  'london',
  'bristol',
  'york',
  'birminham',
  'bath',
];

export const navlinks = [
  { label: 'Home', icon: home, path: '' },
  {
    label: 'Search',
    icon: navSearch,
    path: 'search',
  },
  {
    label: 'Add Car',
    icon: plus,
    path: 'add-car',
  },
];
